### ISSUE TITLE
大神你好，关于你的这个批量更改cocodataset_annotations的image_id.py 

### ISSUE THREAD

**Issue by MheadHero** [HelloSZS/common_tools_in_OD#1]
大神你好，我来自马来西亚。我在网上下载了这个dataset，请问我要如何使用您的code呢？因为他很多图片的名字都不易，搞得我在弄od的时候很麻烦。如果你有看到，请回复。我在线等。先谢谢你！
![image](https://user-images.githubusercontent.com/24875124/169774001-f752065d-a7b4-4e9c-b2db-623e0f7ed5b5.png)

**Comment by HelloSZS** [comment]
TACO数据集的标注是用了COCO数据集的标注格式。我想你首先需要去TACO的github上面了解这个数据集文件夹里面的文件结构。关于"因为他很多图片的名字都不易"这句话是指：你不清楚它这个文件夹的文件目录结构？

我的code不是用来做OD的，而是用来处理VOC和COCO之间的格式转换，以及处理VOC的xml标注格式文件和COCO的json格式文件的一些问题。

**Comment by MheadHero** [comment]
不是不易 是不一样，因为我看到您写的这个批量更改cocodataset_annotations的image_id.py是可以把全部imageid从写成号码罢了对不

**Comment by MheadHero** [comment]
那句不易是写错了 哈哈

**Comment by MheadHero** [comment]
你也有听过tacodataset吗？我还以为他很冷门

**Comment by MheadHero** [comment]
就我想问我要怎么用你的这个"批量更改cocodataset_annotations的image_id.py" 在cmd里面 !python 批量更改cocodataset_annotations的image_id.py 就可以了吗？

**Comment by HelloSZS** [comment]
因为第一次用github写md文档，我不知道怎么插入图片，排版什么的，详细的使用教程我写在了这里：
https://blog.csdn.net/weixin_42362903/article/details/124869047?spm=1001.2014.3001.5501

**Comment by HelloSZS** [comment]
> 易 是不一样，因为我看到您写的这个批量更改cocodataset_annotations的image_id.py是可以把全部imageid从写成号码罢了对不

是的

**Comment by MheadHero** [comment]
> 因为第一次用github写md文档，我不知道怎么插入图片，排版什么的，详细的使用教程我写在了这里： https://blog.csdn.net/weixin_42362903/article/details/124869047?spm=1001.2014.3001.5501

其实我有读到你的这个 不过我真的是小白啊 就我有了你这这个.py文件后要怎么运行他 （笑死）

**Comment by MheadHero** [comment]
![image](https://user-images.githubusercontent.com/24875124/169785153-c1112c0e-4402-463e-bb12-9a1bb96f3f18.png)
就为什么我运行的时候会这样？

**Comment by MheadHero** [comment]
![image](https://user-images.githubusercontent.com/24875124/169786108-f325ff27-78bd-4b8b-a20a-9da72b868465.png)
为什么会这样勒

好像是下面这边出问题了：

    for i, img_dict in enumerate(old_id_list):
        # new_name new_id old_name old_id
        i = i + start_id
        new_id, new_name = str(i), str(i)+'.jpg'
        convert_table.append(zip(new_name, new_id, img_dict['file_name'], img_dict['id']))
        oldName_newId_dict[str(img_dict['file_name'].split('.')[0])] = new_id 《《这是第35行

**Comment by MheadHero** [comment]
楼主 我想知道 oldName_newId_dict 里面存的是什么

**Comment by MheadHero** [comment]
btw 大神 你的code好像很多问题哦， 我改了很多才用到，可能是我的dataset构造不一样把。不管怎样 谢谢你！
